# Generated by Django 3.2.7 on 2021-12-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blog_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='img',
            new_name='Img',
        ),
    ]
